/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Academics generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Academics`")
@IdClass(AcademicsId.class)
public class Academics implements Serializable {

    private Date academicYear;
    private String standard;
    private List<Subjects> subjectses = new ArrayList<>();

    @Id
    @Temporal(TemporalType.DATE)
    @Column(name = "`Academic Year`", nullable = false)
    public Date getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(Date academicYear) {
        this.academicYear = academicYear;
    }

    @Id
    @Column(name = "`Standard`", nullable = false, length = 255)
    public String getStandard() {
        return this.standard;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }


    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "academics")
    public List<Subjects> getSubjectses() {
        return this.subjectses;
    }

    public void setSubjectses(List<Subjects> subjectses) {
        this.subjectses = subjectses;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Academics)) return false;
        final Academics academics = (Academics) o;
        return Objects.equals(getAcademicYear(), academics.getAcademicYear()) &&
                Objects.equals(getStandard(), academics.getStandard());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcademicYear(),
                getStandard());
    }
}

