/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcademicYear generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ACADEMIC_YEAR`")
public class AcademicYear implements Serializable {

    private String academicYear;
    private Integer startYear;
    private Integer endYear;
    private List<Academics> academicses = new ArrayList<>();

    @Id
    @Column(name = "`ACADEMIC_YEAR`", nullable = false, length = 255)
    public String getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }

    @Column(name = "`START_YEAR`", nullable = true, scale = 0, precision = 10)
    public Integer getStartYear() {
        return this.startYear;
    }

    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    @Column(name = "`END_YEAR`", nullable = true, scale = 0, precision = 10)
    public Integer getEndYear() {
        return this.endYear;
    }

    public void setEndYear(Integer endYear) {
        this.endYear = endYear;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "academicYearByAcademicYear")
    public List<Academics> getAcademicses() {
        return this.academicses;
    }

    public void setAcademicses(List<Academics> academicses) {
        this.academicses = academicses;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AcademicYear)) return false;
        final AcademicYear academicYearInstance = (AcademicYear) o;
        return Objects.equals(getAcademicYear(), academicYearInstance.getAcademicYear());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcademicYear());
    }
}

