/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class SubjectsId implements Serializable {

    private String standard;
    private Date academicYear;
    private String subjectName;

    public String getStandard() {
        return this.standard;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    public Date getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(Date academicYear) {
        this.academicYear = academicYear;
    }

    public String getSubjectName() {
        return this.subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Subjects)) return false;
        final Subjects subjects = (Subjects) o;
        return Objects.equals(getStandard(), subjects.getStandard()) &&
                Objects.equals(getAcademicYear(), subjects.getAcademicYear()) &&
                Objects.equals(getSubjectName(), subjects.getSubjectName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStandard(),
                getAcademicYear(),
                getSubjectName());
    }
}
