/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.school_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.student_usecase.school_db.Subjects;
import com.student_usecase.school_db.SubjectsId;


/**
 * ServiceImpl object for domain model class Subjects.
 *
 * @see Subjects
 */
@Service("School_DB.SubjectsService")
public class SubjectsServiceImpl implements SubjectsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SubjectsServiceImpl.class);


    @Autowired
    @Qualifier("School_DB.SubjectsDao")
    private WMGenericDao<Subjects, SubjectsId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Subjects, SubjectsId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "School_DBTransactionManager")
    @Override
	public Subjects create(Subjects subjects) {
        LOGGER.debug("Creating a new Subjects with information: {}", subjects);
        Subjects subjectsCreated = this.wmGenericDao.create(subjects);
        return subjectsCreated;
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public Subjects getById(SubjectsId subjectsId) throws EntityNotFoundException {
        LOGGER.debug("Finding Subjects by id: {}", subjectsId);
        Subjects subjects = this.wmGenericDao.findById(subjectsId);
        if (subjects == null){
            LOGGER.debug("No Subjects found with id: {}", subjectsId);
            throw new EntityNotFoundException(String.valueOf(subjectsId));
        }
        return subjects;
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public Subjects findById(SubjectsId subjectsId) {
        LOGGER.debug("Finding Subjects by id: {}", subjectsId);
        return this.wmGenericDao.findById(subjectsId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "School_DBTransactionManager")
	@Override
	public Subjects update(Subjects subjects) throws EntityNotFoundException {
        LOGGER.debug("Updating Subjects with information: {}", subjects);
        this.wmGenericDao.update(subjects);

        SubjectsId subjectsId = new SubjectsId();
        subjectsId.setStandard(subjects.getStandard());
        subjectsId.setAcademicYear(subjects.getAcademicYear());
        subjectsId.setSubjectName(subjects.getSubjectName());

        return this.wmGenericDao.findById(subjectsId);
    }

    @Transactional(value = "School_DBTransactionManager")
	@Override
	public Subjects delete(SubjectsId subjectsId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Subjects with id: {}", subjectsId);
        Subjects deleted = this.wmGenericDao.findById(subjectsId);
        if (deleted == null) {
            LOGGER.debug("No Subjects found with id: {}", subjectsId);
            throw new EntityNotFoundException(String.valueOf(subjectsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public Page<Subjects> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Subjects");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<Subjects> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Subjects");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service School_DB for table Subjects to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "School_DBTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }



}

