/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.student_usecase.studentportal_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * StudentAcademics generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`STUDENT_ACADEMICS`", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`STUDENT_ID`", "`ACADEMIC_YEAR`", "`STANDARD`", "`ROLL_NUMBER`"})})
@IdClass(StudentAcademicsId.class)
public class StudentAcademics implements Serializable {

    private Integer studentId;
    private Date academicYear;
    private String standard;
    private int rollNumber;
    private Academics academics;
    private StudentDetails studentDetails;
    private List<Results> resultses = new ArrayList<>();

    @Id
    @Column(name = "`STUDENT_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    @Id
    @Temporal(TemporalType.DATE)
    @Column(name = "`ACADEMIC_YEAR`", nullable = false)
    public Date getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(Date academicYear) {
        this.academicYear = academicYear;
    }

    @Id
    @Column(name = "`STANDARD`", nullable = false, length = 255)
    public String getStandard() {
        return this.standard;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    @Column(name = "`ROLL_NUMBER`", nullable = false, scale = 0, precision = 10)
    public int getRollNumber() {
        return this.rollNumber;
    }

    public void setRollNumber(int rollNumber) {
        this.rollNumber = rollNumber;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumns({
            @JoinColumn(name = "`ACADEMIC_YEAR`", referencedColumnName = "`ACADEMIC_YEAR`", insertable = false, updatable = false),
            @JoinColumn(name = "`STANDARD`", referencedColumnName = "`STANDARD`", insertable = false, updatable = false)        })
    public Academics getAcademics() {
        return this.academics;
    }

    public void setAcademics(Academics academics) {
        if(academics != null) {
            this.academicYear = academics.getAcademicYear();
            this.standard = academics.getStandard();
        }

        this.academics = academics;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`STUDENT_ID`", referencedColumnName = "`STUDENT_ID`", insertable = false, updatable = false)
    public StudentDetails getStudentDetails() {
        return this.studentDetails;
    }

    public void setStudentDetails(StudentDetails studentDetails) {
        if(studentDetails != null) {
            this.studentId = studentDetails.getStudentId();
        }

        this.studentDetails = studentDetails;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "studentAcademics")
    public List<Results> getResultses() {
        return this.resultses;
    }

    public void setResultses(List<Results> resultses) {
        this.resultses = resultses;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof StudentAcademics)) return false;
        final StudentAcademics studentAcademics = (StudentAcademics) o;
        return Objects.equals(getStudentId(), studentAcademics.getStudentId()) &&
                Objects.equals(getAcademicYear(), studentAcademics.getAcademicYear()) &&
                Objects.equals(getStandard(), studentAcademics.getStandard());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStudentId(),
                getAcademicYear(),
                getStandard());
    }
}

